# fly.toml app configuration file generated for compulsoryassignment-1-y on 2026-08-16T11:40:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'compulsoryassignment-1-y'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
